name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  

jobs:
  basic-checks:
    name: Basic Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx prettier --check "apps/**/*.{js,ts,html,css,scss,json}" 
        #"libs/**/*.{js,ts,html,css,scss,json}"

      - name: Lint
        run: npm run lint:client

      - name: Build
        run: npm run build:client

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: basic-checks
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run test:client
        
  server-build:
    name: Server Build
    runs-on: ubuntu-latest
    needs: basic-checks
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          
      - name: Build with Maven
        run: npm run build:server
        
  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest
    needs: server-build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install dependencies
        run: npm ci
          
      - name: Run DTO Request Tests
        run: npm run test:server:dto
        continue-on-error: true
        
      - name: Run Entity Tests  
        run: npm run test:server:entity
        continue-on-error: true
        
      - name: Run Unit/DTO Tests
        run: npm run test:server:unit
        continue-on-error: true
        
      - name: Run REST Controller Tests
        run: npm run test:server:rest
        continue-on-error: true
        
      - name: Run All Server Tests
        run: npm run test:server